### ISSUE TITLE
Cannot open include file: 'caffe/include_symbols.hpp': No such file or directory

### ISSUE THREAD

**Issue by lunzueta** [willyd/caffe#19] opened 2016-08-26 09:41 UTC
Hi @willyd. I've followed the new installation instructions (as explained here: https://github.com/willyd/caffe/tree/windows-cmake), but when compiling I get the error I've put in the title. I can't find that file anywhere in the repo nor in the cmake-generated build folder. It's only referenced in the file C:\caffe\build\caffe/export.hpp

What should be done?

Thanks

**Comment by willyd** [comment] 2016-08-26 13:47
@lunzueta are you using the Visual Studio or Ninja generator? I mostly use Ninja, I tried  to make sure that VS works too (see the build scripts in scripts/appveyor and also the build logs on appveyor). 

What is your version of CMake? You need 3.4+. I use 3.5 and 3.6.

Are you building a shared library, i.e. BUILD_SHARED_LIBS=ON? If yes, I might have an idea on what's wrong.

In main CMakeLists.txt change:

``` CMake
# definition needed to include CMake generated files
add_definitions(-DCMAKE_WINDOWS_BUILD)
```

to 

``` CMake
if(NOT BUILD_SHARED_LIBS)
  # definition needed to include CMake generated files
  add_definitions(-DCMAKE_WINDOWS_BUILD)
endif()
```

If that solves the problem can you submit a PR to the windows-cmake branch? I'll merge it.

**Comment by lunzueta** [comment] 2016-08-26 16:50
Initially, I tried to use Ninja, but I couldn't configure the project properly with the cmake command line (I got some configuration errors). So, then I used cmake-gui, configured it selecting the generator "Visual Studio 12 2013 Win64", and for those dependencies that weren't directly detected by cmake, I manually included the paths to those downloaded by the conda package manager to C:\Anaconda2\envs\caffe\Library

I'm using CMake 3.5.1 and I had BUILD_SHARED_LIBS=OFF

**Comment by willyd** [comment] 2016-08-27 01:41
If you can repro the CMake configure errors you got with Ninja and output that to a file I would be glad to look at it. 

The caffe include_symbols.hpp is generated by some post_build event. For some reason it may not be executed at all or just fail to generate the file. You can put some debug message(STATUS "this is a debug message") in this [file](https://github.com/willyd/caffe/blob/windows-cmake/cmake/WindowsCreateLinkHeader.cmake) and see if anything shows up in the output window in VS. Put your debug message(STATUS "") in the `if(CMAKE_SCRIPT_MODE_FILE)`.

**Comment by lunzueta** [comment] 2016-08-27 10:22
I attach the two log files that generates CMake so that you can see what happened when I tried to configure it for Ninja. I think that the problem might be that even if I run the command `"%VS120COMNTOOLS%..\..\VC\vcvarsall.bat" amd64` to setup the msvc compiler, it strangely gets MinGW, and this might fail in later stages of the configuration.

[CMakeOutput.txt](https://github.com/willyd/caffe/files/440599/CMakeOutput.txt)
[CMakeError.txt](https://github.com/willyd/caffe/files/440598/CMakeError.txt)

**Comment by willyd** [comment] 2016-08-29 12:24
Weird, maybe CMake checks for Mingw first? I don't have gcc installed but appveyor does and it does not conflict. Maybe [this post](https://cmake.org/pipermail/cmake/2012-September/051986.html) can be of help?

Otherwise it should work from VS too. Make sure you start the VS devenv from the same command line you `activate`d the conda environment.

If you can get the build output from VS and attach it here I will have a look.

**Comment by lunzueta** [comment] 2016-08-30 17:24
Thanks @willyd, that helped. In the end, I used the following command to specify the compiler, and by the way to skip cudnn, because otherwise I had some compilation errors later:

```
cmake -GNinja -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -DUSE_CUDNN=OFF -DBLAS=Open -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_MODULE_PATH=%CMAKE_MODULE_PATH% -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH% -DCMAKE_INSTALL_PREFIX=.\install ..\
```

So, I could compile Caffe with Ninja, and I was able to use the generated pycaffe with NVIDIA DIGITS in Windows 10 (I could train LeNet with MNIST correctly). But afterwards, I tried to use the C++ Caffe library externally and I had some problems generating the Visual Studio solution of the project with CMake (I don't want to use Ninja in this case, at least for now). I used `find_package(Caffe)` with the generated CaffeConfig.cmake file, and I had the errors I attach here with some of the dependencies. Any suggestions?

By the way, do you think it's necessary to include CMake in the caffe environment installed in Anaconda? For example, the cmake-gui installed there can't run, because there are some Qt files missing (I guess they'd be those added when running windeployqt.exe, included in Qt's bin folder). I'd rather use the CMake program I already had installed. Same for OpenCV.

[cmake-output.txt](https://github.com/willyd/caffe/files/445463/cmake-output.txt)

**Comment by willyd** [comment] 2016-08-31 01:10
@lunzueta You need to pass the `-DCMAKE_MODULE_PATH=%CMAKE_MODULE_PATH% -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%` options to your CMake configure too. If you use cmake-gui you can set those variables too. Make sure you activate the caffe environment and call set_cmake_vars.bat. 

You need to do so because the conda packages you installed (when following the README.md) provided custom FindBoost.cmake, FindZLIB.cmake, etc. CMAKE_MODULE_PATH defines where CMake looks to find those files. CMAKE_PREFIX_PATH defines where cmake looks for <packagename>config.cmake files. This is necessary to ensure that the packages can be built on a machine and used on another, i.e. avoiding absolute include and library paths.

Yeah I got the same Qt error when trying to use the cmake-gui that comes with the cmake conda package. If I understand correctly this cmake-gui can be fixed by running windeployqt.exe. Where can I find this executable? You can definitely use your own cmake. You can either prepend to your path to make sure the system cmake is used or force the uninstall in your conda env using:

``` shell
> conda uninstall cmake --force
```

**Comment by lunzueta** [comment] 2016-08-31 18:54
Hi @willyd, I've done different tests to link Caffe externally to a project, but I still have this problem. I attach a couple of files: (1) a simple CMakeLists.txt file to generate a dummy library which links externally Caffe and (2) the results cmake gives me, when generating it with Ninja, like this (after preparing the conda environment):

```
cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_MODULE_PATH=%CMAKE_MODULE_PATH% -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH% ..\
```

Thanks for your help

[CMakeLists.txt](https://github.com/willyd/caffe/files/448033/CMakeLists.txt)
[cmake-output.txt](https://github.com/willyd/caffe/files/448032/cmake-output.txt)

**Comment by willyd** [comment] 2016-08-31 19:11
Hi @lunzueta, the CaffeConfig.cmake will not resolve the other libs for you, this is something I still need to fix. Try with this (untested) CMakeLists.txt instead.
[CMakeLists.txt](https://github.com/willyd/caffe/files/448073/CMakeLists.txt)

**Comment by willyd** [comment] 2016-08-31 19:12
BTW, it should work with the Visual Studio generator too. Let me know if it does not.

**Comment by lunzueta** [comment] 2016-09-01 06:42
OK, understood. I thought this could be done somehow from CaffeConfig.cmake, but I didn't check this possibility in detail. I forgot to remark that you can find the file windeployqt.exe in the bin folder of your Qt installation. This step is necessary for deploying the programs that have Qt as a dependence (you compiled cmake from source, did you?). Here you have some instructions of how to use it: http://doc.qt.io/qt-5/windows-deployment.html

**Comment by willyd** [comment] 2016-09-01 12:17
> I thought this could be done somehow from CaffeConfig.cmake, but I didn't check this possibility in detail.

You are right the CaffeConfig.cmake file should include calls to `find_package(Boost)` or rather to `find_dependency` and so on so that a consuming project like yours only has to do `find_package(Caffe)`.

> forgot to remark that you can find the file windeployqt.exe in the bin folder of your Qt installation. This step is necessary for deploying the programs that have Qt as a dependence (you compiled cmake from source, did you?). Here you have some instructions of how to use it: http://doc.qt.io/qt-5/windows-deployment.html

Thanks for the info. No I did not build cmake from source. I am just using the conda-forge cmake package. I reported the issue [upstream](https://github.com/conda-forge/cmake-feedstock/issues/12).

**Comment by lunzueta** [comment] 2016-09-03 10:09
Hi @willyd. I'm still a bit stuck with this. I used that CMake code you shared to find the dependencies, a little bit changed, like this, because LMDB, LevelDB and Snappy shouldn't appear as Boost components:

```
FIND_PACKAGE( Boost COMPONENTS atomic chrono date_time filesystem python system thread )
FOREACH( _pkg ZLIB gflags glog OpenCV protobuf HDF5 OpenBLAS LevelDB LMDB Snappy )
FIND_PACKAGE( ${_pkg} )
ENDFOREACH()
FIND_PACKAGE( Caffe )
```

This way, CMake found the paths to the dependencies, but when compiling in Visual Studio I had problems with OpenBLAS and ProtoBuf.

In the case of OpenBLAS, even if CMake found the path to the directory C:/Anaconda2/envs/caffe/Library/lib/cmake/openblas, then when generating the VS solution I see that it tries to link the file OpenBLAS.lib, which doesn't exist (it should be libopenblas.dll.a).

In the case of ProtoBuf in cmake-gui I can see that all the required files were detected with the correct absolute path, but then I'm in VS I see that it tries to link libprotobuf.lib (which is the correct name), but without its path included, so it can't link.

I've been checking the CMake files of each of these dependencies, but I can't figure out what to change to make this work.

**Comment by willyd** [comment] 2016-09-03 14:35
Hi @lunzueta I just followed the README.md on a different computer and everything works on my side. 

After installing caffe, I do the following (from the **SAME** console with activated environment):

```
:: caffe-test contains a dummy CMakeLists.txt
cd caffe-test
mkdir build
cd build
cmake -G"Visual Studio 12 2013 Win64" -DBLAS=Open -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_MODULE_PATH=%CMAKE_MODULE_PATH% -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH% -DCMAKE_INSTALL_PREFIX=install ..\
devenv caffe-test.sln
```

and I get the following libs in the release config:

```
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib
C:\Users\guillaume\Documents\Work\caffe\build\lib\caffe.lib
C:\Users\guillaume\Documents\Work\caffe\build\lib\proto.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\lib\boost_python-vc120-mt-1_61.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\lib\boost_thread-vc120-mt-1_61.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\lib\boost_atomic-vc120-mt-1_61.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\lib\boost_chrono-vc120-mt-1_61.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\lib\glog.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\Lib\gflags.lib
shlwapi.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\lib\libprotobuf.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\alt\lib\alt-hdf5_hl.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\alt\lib\alt-hdf5.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\lib\lmdb.lib
ntdll.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\lib\leveldb.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\lib\boost_date_time-vc120-mt-1_61.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\lib\boost_filesystem-vc120-mt-1_61.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\lib\boost_system-vc120-mt-1_61.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\lib\snappy_static.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\alt\lib\alt-zlib.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\lib\x64\cudart.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\lib\x64\curand.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\lib\x64\cublas.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\lib\x64\cublas_device.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\x64\vc12\lib\opencv_highgui310.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\x64\vc12\lib\opencv_imgcodecs310.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\x64\vc12\lib\opencv_imgproc310.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\x64\vc12\lib\opencv_core310.lib
C:\Users\guillaume\Anaconda2\envs\caffe\Library\lib\libopenblas.dll.a
C:\Users\guillaume\Anaconda2\envs\caffe\libs\python27.lib
```

Here is my CMakeLists.txt file
[CMakeLists.txt](https://github.com/willyd/caffe/files/453415/CMakeLists.txt)

However, I had some trouble with cmake-gui. Make sure the `CMAKE_MODULE_PATH` and `CMAKE_PREFIX_PATH` are correctly set in there. I don't know why they don't show up in cmake-gui. I will raise the issue with CMake.

Also, please update to the latest commit as some files were missing from the install.

You can trace CMake behavior with message(STATUS) commands. Look in your anaconda install path for `envs\caffe\Library\cmake\modules\FindOpenBLAS.cmake` to see if it actually uses this file.

**Comment by lunzueta** [comment] 2016-09-03 15:48
Hi @willyd you are right! If I run cmake from the console that way, and I compile from the configured solution in VS, everything works fine. The problem comes once I open that configuration with cmake-gui, even if I run it from that same console (with the environment activated). I can see there that it still can be configured further, a couple times more, and then once I finish configuring and generating the solution again, when I go to VS I get those problems I mentioned before.

**Comment by lunzueta** [comment] 2016-09-04 08:38
Hi @willyd. After your last commit, now I have this error when linking caffe in another project (I didn't have this error before):

```
cublas_device.lib(ztrmm_sm35_cpp2asm.asm.obj) : error LNK2019: unresolved external symbol __cudaRegisterLinkedBinary_69_tmpxft_00000fd4_00000000_11_ztrmm_sm35_cpp2asm_asm_compute_37_cpp1_ii_2af62f32 referenced in function "void __cdecl __sti____cudaRegisterAll_69_tmpxft_00000fd4_00000000_11_ztrmm_sm35_cpp2asm_asm_compute_37_cpp1_ii_2af62f32(void)" (?__sti____cudaRegisterAll_69_tmpxft_00000fd4_00000000_11_ztrmm_sm35_cpp2asm_asm_compute_37_cpp1_ii_2af62f32@@YAXXZ)
```

I've reviewed your changes, but I don't know how these can be related to this linking error. Any idea?

**Comment by willyd** [comment] 2016-09-05 23:39
Hi @lunzueta. No I have never seen this error before. Are you linking the cublas libs? Are you linking the good versions x64 (and not x86)? I will try to reproduce this when I have time. Is the project you have trouble with on github?

**Comment by lunzueta** [comment] 2016-09-06 17:11
@willyd have a look at this more elaborated dummy library project (https://github.com/lunzueta/dummylib). We can use this for testing all this. Thanks.

**Comment by willyd** [comment] 2016-09-13 00:54
@lunzueta I have been able to reproduce the problem but I could not find a fix for it yet. In the mean time I suggest that you try to use a shared library (I got your project to link when configuring caffe with BUILD_SHARED_LIBS=ON).

**Comment by willyd** [comment] 2016-09-13 02:39
@lunzueta could you try to build a static caffe library and build your own project without linking to it but by adding the .obj files found in the caffe build folder to your project. You can do this in CMake by adding .obj files to the `add_library` call or by using Add > Existing Item in VS.

Let me know if this solves the linker error and if you can run your project correctly.

**Comment by lunzueta** [comment] 2016-09-13 18:41
Hi @willyd. I've been able to train nets correctly both in Debug and Release with the library where Caffe, built as a shared library, is linked externally as a dependence. So, this worked. However, a debug assertion failed when saving a HDF5 file, relying on Caffe's functionalities for this (in a similar way to this code: https://github.com/BVLC/caffe/blob/master/src/caffe/test/test_hdf5_output_layer.cpp). It said that the failure was in:

```
f:\dd\vctools\crt\crtw32\misc\dbgheap.c
Line: 1424
Expression: _pFirstBlock == pHead
```

This is very strange because I don't have that path available in my PC. Do you recognize this path? Might it be something related to Caffe's 3rd parties included in the Conda package?

I don't get this failure when I link Microsoft's Caffe version to my library, so this has to be something from this Caffe version.

Next I'll try to do the same thing when Caffe is built statically and adding those .obj files, as you suggest, and I'll tell you.

**Comment by lunzueta** [comment] 2016-09-13 19:47
I'm a bit confused with the .obj files to be added. I see there are many and none of them seem to be appropriate to be added in my project, as they seem to correspond to the Caffe projects that link the static library. Which would they be?

**Comment by willyd** [comment] 2016-09-13 20:53
> Hi @willyd. I've been able to train nets correctly both in Debug and Release with the library where Caffe, built as a shared library, is linked externally as a dependence. So, this worked.

Good.

> This is very strange because I don't have that path available in my PC. Do you recognize this path? Might it be something related to Caffe's 3rd parties included in the Conda package?

Never played too much with the HDF5 layers of caffe so this bug might always have been present. No this path does not tell me anything. I tried to pay special care to HDF5 since there is already a HDF5 version installed with Anaconda. Can you confirm that your caffe links to libraries that have the `alt` prefix, e.g. alt-zlib.lib, alt-hdf5.lib, etc. You could also confirm which hdf5 library gets loaded by looking at the Output Window in the debugger.

> I don't get this failure when I link Microsoft's Caffe version to my library, so this has to be something from this Caffe version.

Just curious how do you link the caffe library to yours and not lose the symbols? Add the libcaffe.vcxproj as a reference in your solution and tell VS to link in the object files instead?

> I'm a bit confused with the .obj files to be added. I see there are many and none of them seem to be appropriate to be added in my project, as they seem to correspond to the Caffe projects that link the static library. Which would they be?

Under the build folder I have src\caffe\CMakeFiles\

any .obj file that is related to the caffe lirbary is in there (and subfolders). Add them all. Clear enough now?

**Comment by lunzueta** [comment] 2016-09-14 19:33
Hi @willyd 

> Can you confirm that your caffe links to libraries that have the `alt` prefix, e.g. alt-zlib.lib, alt-hdf5.lib, etc. You could also confirm which hdf5 library gets loaded by looking at the Output Window in the debugger.

Yes, I see that the `alt` files that are linked in the project are: alt-hdf5_hl.lib, alt-hdf5.lib and alt-zlib.lib

By the way, the HDF5 library version used in Microsoft's Caffe is this: https://www.nuget.org/packages/hdf5-v120-complete/

> Just curious how do you link the caffe library to yours and not lose the symbols? Add the libcaffe.vcxproj as a reference in your solution and tell VS to link in the object files instead?

I created a VS project for my library in a similar way to those already included in Caffe's VS solution, with "libcaffe" as a dependence and with the "Use Library Dependency Inputs" property activated. Then, I included this project in Caffe's VS solution, and compiled. Not my favorite way for this. I'd prefer the CMake way...

> Under the build folder I have src\caffe\CMakeFiles\ any .obj file that is related to the caffe lirbary is in there (and subfolders). Add them all. Clear enough now?

Yes, it worked too!

**Comment by willyd** [comment] 2016-09-15 00:07
@lunzueta 

> Yes, it worked too!

Thanks for trying this. By it worked I guess you mean it linked and your program could run (apart from the aforementioned HDF5 error)? If this is the case, it seems that I am trying to force the linker to include symbols it should not. The only thing that I find weird is that other .exe and .dll (.pyd) in caffe source tree compile fine with this. I will try to change the force linking feature to remove this problem. 

As for the HDF5 problem. Can you confirm if the HDF5 tests pass? To build the tests you need to run:

```
> ninja test.testbin
```

from the build folder.

From the root caffe folder run:

```
> build\test\test.testbin.exe --gtest_filter=*HDF5*
```

On my machine I get 8/8 pass.

**Comment by willyd** [comment] 2016-09-15 02:38
@lunzueta Please try the latest commit with the static library build. Let me know how this goes.

**Comment by lunzueta** [comment] 2016-09-15 18:58
Yes, when I said it worked I meant that I was able to train/test models using my library with Caffe built statically as a dependence, in the same way as with Caffe built dynamically as a dependence.

I confirm that the HDF5 test you mention passes normally in my side too. This is weird because I still have that problem I mentioned before when I try to save HDF5 files using my library relying on Caffe's functionalities for that. This isn't very different from that test in Caffe. And I'm not getting this error when I link Microsoft's Caffe to my library. I don't understand either where does that strange path cited in the assertion failure come from. My impression is that it should be from a dependence linked to my library (Caffe or its dependences). Should we try to link another HDF5 version to Caffe? I guess this would need some changes in Caffe's CMake configuration. How would you do that? Thanks

**Comment by willyd** [comment] 2016-09-15 23:59
@lunzueta If possible could you make a small example that reproduces this behavior?

If you want to link a different HDF5 the easiest option is to hack the CMake script:
Comment this line:
https://github.com/willyd/caffe/blob/windows-cmake/cmake/Dependencies.cmake#L36
And replace it with

```
set(HDF5_INCLUDE_DIRS path/to/hdf5/include)
set(HDF5_HL_INCLUDE_DIR path/to/hdf5/include)
set(HDF5_LIBRARIES optimized hdf5.lib optimized hdf5_hl.lib debug hdf5_D.lib debug hdf5_hl_D.lib)
set(HDF5_FOUND TRUE)
```

Please make sure that the library names are right and that you put in the full path. Paths must be UNIX style with slashes `/`.

**Comment by lunzueta** [comment] 2016-09-16 21:13
Hi @willyd. Thanks for the explanation, I'll test other HDF5 versions and I'll tell you if things change.

BTW, I've uploaded a small example [here](https://github.com/lunzueta/dummylib). You can run this example by linking your Caffe version with CMake, but also Microsoft's Caffe version as explained above (there's a folder called 'windows' with the required VS projects to be included in Caffe's VS solution). The assertion failure can be seen in Debug mode.

**Comment by lunzueta** [comment] 2016-09-17 13:38
Hi @willyd. I found something interesting regarding the dependence of HDF5. I changed the cmake script as you suggested, more specifically like this:

```
set(is_required REQUIRED)
set(HDF5_INCLUDE_DIRS C:/NugetPackages/hdf5-v120-complete.1.8.15.2/lib/native/include)
set(HDF5_HL_INCLUDE_DIR C:/NugetPackages/hdf5-v120-complete.1.8.15.2/lib/native/include)
set(HDF5_LIBRARIES
C:/NugetPackages/hdf5-v120-complete.1.8.15.2/lib/native/lib/x64/hdf5.lib
C:/NugetPackages/hdf5-v120-complete.1.8.15.2/lib/native/lib/x64/hdf5_hl.lib)
set(HDF5_FOUND TRUE)
```

This version corresponds to that used in Microsoft's Caffe, where as you can see it doesn't contain specific builds for Debug and Release modes, so that's why I included them like this in the cmake script.
Then I run the test successfully in Release, but in Debug I got the same failure as before. I've seen that in Microsoft's Caffe HDF5 version's folder, zlib.lib is also contained. Maybe we should replace alt-zlib.lib by that one too? Why is there that specific version of zlib? Meanwhile, I'll test to change this too, and see if that solves the HDF5 test issue in Debug mode.

**Comment by willyd** [comment] 2016-09-17 20:12
@lunzueta Thanks for the detailed report. This makes me think that HDF5 might not be to blame here since it the Debug assertion is raised regardless of the version. If nuget hdf5 provides its own zlib it's probably not a good idea to mix it with my own. Since this is a Debug assertion it is normal that you get this error only in Debug. This does not mean that nothing bad happens in Release. To this looks like a memory corruption. Most likely a mix of libcmt.lib and msvcrt.lib (static and shared crt). I will double check my dependencies to see if any links to the static runtime. I will also try to reproduce the problem with your sample project.

> Maybe we should replace alt-zlib.lib by that one too?

Yes and no. I use a single version zlib for evey dependency. So it might just mess things up a little more.

> Why is there that specific version of zlib?

The prefix is just there to avoid name clashes with other zlib provided by the conda manager for example.

**Comment by willyd** [comment] 2016-09-19 00:14
@lunzueta I updated dummylib and run the tests in both debug and release with no error. Should I test something else? I don't get this assertion failure you were mentioning.

**Comment by lunzueta** [comment] 2016-09-19 18:02
Let's review all the testing process, to see if we do different things:

1) Compilation of Caffe:

```
C:\(CAFFE_PATH)\build>activate caffe
C:\(CAFFE_PATH)\build>"%VS120COMNTOOLS%..\..\VC\vcvarsall.bat" amd64
C:\(CAFFE_PATH)\build>set_cmake_vars

C:\(CAFFE_PATH)\build>cmake -GNinja -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -DUSE_CUDNN=OFF -DBLAS=Open -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_MODULE_PATH=%CMAKE_MODULE_PATH% -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH% -DCMAKE_INSTALL_PREFIX=.\install ..\
C:\(CAFFE_PATH)\build>ninja
C:\(CAFFE_PATH)\build>ninja install

C:\(CAFFE_PATH)\build>cmake -GNinja -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -DUSE_CUDNN=OFF -DBLAS=Open -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF -DCMAKE_MODULE_PATH=%CMAKE_MODULE_PATH% -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH% -DCMAKE_INSTALL_PREFIX=.\install ..\
C:\(CAFFE_PATH)\build>ninja
C:\(CAFFE_PATH)\build>ninja install
```

2) Generation of dummylib library and testing projects for VS:

```
C:\(CAFFE_PATH)\build>cmake -G"Visual Studio 12 2013 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_MODULE_PATH=%CMAKE_MODULE_PATH% -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH% ..\

C:\(CAFFE_PATH)\build>cmake -G"Visual Studio 12 2013 Win64" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_MODULE_PATH=%CMAKE_MODULE_PATH% -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH% ..\
```

Then, open the VS solution `Project.sln` of dummylib, compile `dl` and `tests` projects, and run `tests`. The failure appears in Debug mode (I still get the failure).

**Comment by willyd** [comment] 2016-09-19 18:39
I follow the same procedure with a few exceptions:

1) Compilation of Caffe
I create a build_release and build_debug folder to build caffe. I use the same CMAKE_INSTALL_PREFIX so the debug and release build get installed in the same folder and I don't specify the compiler and some other options:

```
C:\(CAFFE_PATH)>mkdir build_rel && cd build_rel
C:\(CAFFE_PATH)\build_rel>activate caffe
C:\(CAFFE_PATH)\build_rel>"%VS120COMNTOOLS%..\..\VC\vcvarsall.bat" amd64
C:\(CAFFE_PATH)\build_rel>set_cmake_vars

C:\(CAFFE_PATH)\build_rel>cmake -GNinja  -DBLAS=Open -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_MODULE_PATH=%CMAKE_MODULE_PATH% -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH% -DCMAKE_INSTALL_PREFIX=..\install ..\
C:\(CAFFE_PATH)\build_rel>ninja
C:\(CAFFE_PATH)\build_rel>ninja install

C:\(CAFFE_PATH)\build_rel>cd ..
C:\(CAFFE_PATH)>mkdir build_dbg && cd build_dbg
C:\(CAFFE_PATH)\build_dbg>activate caffe
C:\(CAFFE_PATH)\build_dbg>"%VS120COMNTOOLS%..\..\VC\vcvarsall.bat" amd64
C:\(CAFFE_PATH)\build_dbg>set_cmake_vars

C:\(CAFFE_PATH)\build_dbg> cmake -GNinja -DBLAS=Open -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF -DCMAKE_MODULE_PATH=%CMAKE_MODULE_PATH% -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH% -DCMAKE_INSTALL_PREFIX=..\install ..\
C:\(CAFFE_PATH)\build_dbg>ninja
C:\(CAFFE_PATH)\build_dbg>ninja install
```

2) Generation of dummylib library and testing projects for VS:
Since VS generator does not care about CMAKE_BUILD_TYPE I remove it and I do only one configure pass since debug and release builds are handled using the VS gui.

```
C:\(DUMMYLIB_PATH)\build>cmake -G"Visual Studio 12 2013 Win64" -DCMAKE_MODULE_PATH=%CMAKE_MODULE_PATH% -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH% ..\
```

Then, open the VS solution Project.sln of dummylib, compile dl and tests projects, and run tests. Everything goes well and no assertion is raised.

According to these differences I suspect either:
- Leftovers from the Release build of caffe messes up the Debug build of caffe
- Your mingw install is interfering with the build, maybe there are some programs that can be found in mingw and VS install folder, e.g. link.exe.

Here are two things you could try:
- Try using two different build folders and install to the same folder. 
- Try using a computer without mingw or uninstall mingw.

**Comment by lunzueta** [comment] 2016-09-19 20:03
Bad news. I still get the same failure, after following your suggestions :-(
I'll try all this in another PC, and I'll tell you.

**Comment by lunzueta** [comment] 2016-09-20 07:49
Better news this time. I did the whole thing again but in another PC and it worked in Debug too. So... I'll investigate more in detail what happened in my PC. One difference is that in my PC I use VS Community Edition and in the other one I use Professional Edition, which might have an impact on this. Another one is the Windows version, Windows 10 Home in my PC and Windows 10 Pro in the other PC. I'll also review the differences in the Path. Thanks for your help @willyd. I think we are in the good way :-)

**Comment by willyd** [comment] 2016-09-20 12:17
For your info my PC at home is also Windows 10 Home with VS Community and I don't have the issue there. I will test on my work PC Windows 10 Pro with Visual Studio Pro. I have VS 2013 Update 5 at work (not sure about home) this could matter too so check for differences.

**Comment by lunzueta** [comment] 2016-09-21 20:00
Hi @willyd. I reinstalled Caffe's dependencies with Conda, and this time all worked fine in Debug too. Not sure what happened, but this reinstallation solved the issue. Many thanks for your help!

**Closed as completed** 2016-09-21 20:01 UTC

**Comment by willyd** [comment] 2016-09-21 20:19
Great! I will now continue to update my branch until it is ready for merge. Your help to test the changes is always appreciated. Any other contribution you can make to this process is valued. If you have any comments regarding the caffe build on Windows please share them as it will help me to make the process as painless as possible. The main subjects of interest are:
- **Dependency retrieval**

What's your preference? CMake super-build _à la_ caffe-builder? conda? nuget? My take on this is to use a CMake super-build to enable locally building the dependencies so it's easy for any one who wants to rebuild them on their local machine for easier debugging. This CMake superbuild could potentially be used to generate conda (and even nuget) packages. I like conda cause it integrates well with pycaffe and other python related code like DIGITS. What's your opinion?
- **Build System**

What's your preference? CMake? Visual Studio?

I tend to like CMake better since most dependencies build with CMake and using different VS versions at the same time is less painful. Plus, it will be much easier to keep up with caffe/master. However, a straight VS solution is usually what all windows devs prefer. Again what's your take on this? I know you said you like the way my CMake builds make it possible to install the library and link to it but that is not limited to CMake since all I do is call dumpbin.exe and parse the output with some regex to generate linker instructions.

**Comment by lunzueta** [comment] 2016-09-21 21:25
> Your help to test the changes is always appreciated. Any other contribution you can make to this process is valued. If you have any comments regarding the caffe build on Windows please share them as it will help me to make the process as painless as possible.

Thanks, I will :-)

> What's your preference? CMake super-build _à la_ caffe-builder? conda? nuget? My take on this is to use a CMake super-build to enable locally building the dependencies so it's easy for any one who wants to rebuild them on their local machine for easier debugging. This CMake superbuild could potentially be used to generate conda (and even nuget) packages. I like conda cause it integrates well with pycaffe and other python related code like DIGITS. What's your opinion?

I fully agree with your point of view about having the possibility of rebuilding the dependencies, especially because I think that at some moment we'll need to move to VS2015 or whatever. Regarding Conda or Nuget, I don't really mind one or the other. I'm happy with any of these. So, if you are happier with conda because of pycaffe, that's fine (I'm more interested in the C++ code, but I also use Python sometimes, so I don't mind having to install Python, etc).

> I tend to like CMake better since most dependencies build with CMake and using different VS versions at the same time is less painful. Plus, it will be much easier to keep up with caffe/master.

I also prefer this option, because of the same reasons. As a reference, I like how OpenCV can be built using cmake-gui + VS. It would be great if Caffe could be built in the same way. I also liked how you use ninja for compiling Caffe, as it's much faster than VS, but for external projects where I'd link Caffe, I'd rather use VS, in general. What I found more confusing in your current installation procedure is that it was totally necessary to use cmake commands, instead of cmake-gui, otherwise there were some cmake options and procedures that didn't work correctly (don't really understand why).
